alias l='ls -1'
alias open=xdg-open
alias vi=vim
alias py=python
alias ip3=ipython3
alias tm=tmux
alias ta="tmux a -t"
alias jup="jupyter-lab"
alias pep8="watch -n 0.5 pycodestyle"
alias wgpu="watch -n 0.5 gpustat"
alias autopep8="autopep8 --in-place --aggressive --aggressive"
alias net="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -"
alias gitlog="git log --decorate --graph --oneline --all"
alias ww="watch -n 0.3"
alias cin="ssh -p 22 luan@52.76.219.73"
alias awslog="aws logs get-log-events --log-group-name /aws/sagemaker/TrainingJobs --log-stream-name"
