name: Build Docker image

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Build Docker image 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build Docker image
        run : docker build -f Dockerfile .
